{% set name = "PyMaxflow" %}
{% set version = "1.2.14" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyMaxflow-{{ version }}.tar.gz
  sha256: 57ff9e198f700737e38557d7985e9c95678e7234b51091a0810c8cdd0b25cdf6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - maxflow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pmneila/PyMaxflow
  summary: A mincut/maxflow package for Python
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martibosch
