{% set name = "PyMaxflow" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyMaxflow-{{ version }}.tar.gz
  sha256: 94d7bc9c0c7b5a8bfe8cca87bcce4a4aa3bd749e03c5c5bcf3fb2a7a86e7af90

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - maxflow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pmneila/PyMaxflow
  summary: A mincut/maxflow package for Python
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martibosch
