{% set name = "PyMaxflow" %}
{% set version = "1.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.lower() }}-{{ version }}.tar.gz
  sha256: 19f1668dd718d1451a1ad18902ac674b1b380cda1150c855b5e817f1b0de3095

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - python

test:
  imports:
    - maxflow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pmneila/PyMaxflow
  summary: A mincut/maxflow package for Python
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martibosch
